version: 2.1 
jobs: 
  unit-tests: 
    docker: 
      - image: cimg/node:14.20.0
    steps: 
      - checkout 
      - run: 
          name: "install dependencies" 
          command: yarn 
      - run: 
          name: "run project unit tests" 
          command: yarn redwood test 
  build-app: 
    docker: 
      - image: cimg/node:14.20.0
    steps:
      - checkout 
      - run: 
          name: "install dependencies"
          command: yarn 
      - run: 
          name: "build deploy artifact"
          command: yarn redwood build 
  deploy-qa:
    docker:
      - image: cimg/node:17.1.0
    steps:
      - checkout 
      - run: 
          name: "deploy to QA env" 
          command: echo "Deployed to QA environment with AWS S3 bucket magic or Azure container magic" 

worfklows: 
  deploy-to-qa: 
    jobs: 
      - unit-tests
      - build-app 
      - deploy-qa      

